# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Whales and the Fishing Industry
author: Group 21; Walvis

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/aram-iry/infovis
  path_to_book: docs  
  branch: main 

html:
  use_issues_button: true
  use_repository_button: true
  theme:
    name: pydata_sphinx_theme
    toggle:
      icon: "sun"
      show: false
    default_mode: "light"

# Add launch buttons
launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_static_path: ["_static"]
